# Generated by Django 5.2.1 on 2025-10-21 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='source',
            field=models.CharField(choices=[('web', 'Web Portal'), ('email', 'Email'), ('phone', 'Phone Call'), ('walkin', 'Walk-in'), ('internal', 'Internal')], default='web', max_length=50),
        ),
        migrations.AddField(
            model_name='ticketresponse',
            name='response_type',
            field=models.CharField(choices=[('reply', 'Reply'), ('note', 'Internal Note'), ('system', 'System Update')], default='reply', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketresponse',
            name='visibility',
            field=models.CharField(choices=[('public', 'Visible to Member'), ('internal', 'Internal Staff Only'), ('hidden', 'Hidden from Member')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.ticketcategory'),
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.ticketpriority'),
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.ticketstatus'),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helpdesk.ticketstream'),
        ),
    ]
