# Generated by Django 5.2.7 on 2025-10-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSVP',
        ),
    ]
