# Generated by Django 5.2.1 on 2025-11-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo_news_images/'),
        ),
    ]
