# Generated by Django 5.2.7 on 2025-10-15 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reps', '0002_alter_branch_latitude_alter_branch_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reps.area')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='reps.branch')),
                ('school_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membercategory')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpf_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=200)),
                ('start_year', models.IntegerField(default=2025, help_text='Year when you started teaching')),
                ('membership_status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='member_documents/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reps.area')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reps.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membercategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.school')),
            ],
            options={
                'ordering': ['tpf_number'],
            },
        ),
    ]
