# Generated by Django 5.2.7 on 2025-10-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_member_membership_number_member_residing_address'),
        ('reps', '0002_alter_branch_latitude_alter_branch_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reps.area'),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reps.branch'),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.membercategory'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='residing_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_year',
            field=models.IntegerField(blank=True, default=2025, help_text='Year when you started teaching', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='tpf_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
