# Generated by Django 5.2.7 on 2025-10-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_member_area_alter_member_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_year',
            field=models.IntegerField(default=2025),
        ),
    ]
