# Generated by Django 5.2 on 2026-04-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='start_year',
            field=models.IntegerField(default=2026),
        ),
    ]
