# Generated by Django 5.2.7 on 2026-06-04 00:19

import membership.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_alter_member_start_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='school',
            name='branch',
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='member',
            name='ftra_register_num',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='FTRA registration number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_year',
            field=models.IntegerField(default=membership.models.current_year),
        ),
    ]
