# Generated by Django 5.2 on 2026-07-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_district_approval_workflow'),
        ('reps', '0003_district_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reps.district'),
        ),
    ]
