# Generated by Django 5.2.1 on 2025-10-19 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Will auto-fill if user is selected', max_length=200)),
                ('position', models.CharField(help_text='e.g., President, Vice President, General Secretary, etc.', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Brief biography or description')),
                ('email', models.EmailField(blank=True, help_text='Will auto-fill if user is selected', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers show first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link to an existing website user (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
