# Generated by Django 5.2.7 on 2025-10-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Document Categories'},
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='document_categories', to='auth.group'),
        ),
    ]
