# Generated by Django 5.2.7 on 2025-10-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
    ]
