# Generated by Django 5.2.7 on 2025-10-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0003_alter_documentcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
