# Generated by Django 5.2.1 on 2025-11-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
